services:
  # database
  sqlsrv-api-client:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlsrv-api-client
    hostname: sqlsrv-api-client
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123456!"
    ports:
      - "1433:1433"
